dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'
dotenv: .env
networks:
  default: development
  development:
    verify: False
  rinkeby:
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}
